### ISSUE TITLE
Cannot install due to libtorch conflicting with glog.

### ISSUE THREAD

**Issue by nthai** [facebookresearch/ReAgent#288] opened 2020-07-10 10:36 UTC
Hi.

I followed the steps in the current installation instruction and bumped into an error in the final step when trying to `make`. I am not sure if I did everything perfectly with the installation, but some variable names in libtorch's logging and glog are conflicting.

I believe the issue is known:
* https://github.com/pytorch/pytorch/issues/31822
* https://github.com/pytorch/pytorch/issues/14724

This is the error message I get:

```
Scanning dependencies of target rasp-lib
[  2%] Building CXX object CMakeFiles/rasp-lib.dir/reagent/serving/core/DecisionServiceException.cpp.o
[  4%] Building CXX object CMakeFiles/rasp-lib.dir/reagent/serving/core/ConfigProvider.cpp.o
[  6%] Building CXX object CMakeFiles/rasp-lib.dir/reagent/serving/core/DiskConfigProvider.cpp.o
[  8%] Building CXX object CMakeFiles/rasp-lib.dir/reagent/serving/core/Containers.cpp.o
[ 10%] Building CXX object CMakeFiles/rasp-lib.dir/reagent/serving/core/ActionValueScorer.cpp.o
[ 12%] Building CXX object CMakeFiles/rasp-lib.dir/reagent/serving/core/PytorchActionValueScorer.cpp.o
In file included from /home/libtorch/include/c10/util/Logging.h:28:0,
                 from /home/libtorch/include/c10/core/TensorImpl.h:18,
                 from /home/libtorch/include/ATen/core/TensorBody.h:11,
                 from /home/libtorch/include/ATen/Tensor.h:3,
                 from /home/libtorch/include/ATen/Context.h:4,
                 from /home/libtorch/include/ATen/ATen.h:9,
                 from /home/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/libtorch/include/torch/script.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:5,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/libtorch/include/c10/util/logging_is_not_google_glog.h:19:11: error: redefinition of ‘const int google::GLOG_FATAL’
 const int GLOG_FATAL = 3;
           ^~~~~~~~~~
In file included from /home/anaconda3/envs/myenv/include/glog/logging.h:512:0,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/Headers.h:19,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/ActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/anaconda3/envs/myenv/include/glog/log_severity.h:47:60: note: ‘const int google::GLOG_FATAL’ previously defined here
 const int GLOG_INFO = 0, GLOG_WARNING = 1, GLOG_ERROR = 2, GLOG_FATAL = 3,
                                                            ^~~~~~~~~~
In file included from /home/libtorch/include/c10/util/Logging.h:28:0,
                 from /home/libtorch/include/c10/core/TensorImpl.h:18,
                 from /home/libtorch/include/ATen/core/TensorBody.h:11,
                 from /home/libtorch/include/ATen/Tensor.h:3,
                 from /home/libtorch/include/ATen/Context.h:4,
                 from /home/libtorch/include/ATen/ATen.h:9,
                 from /home/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/libtorch/include/torch/script.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:5,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/libtorch/include/c10/util/logging_is_not_google_glog.h:20:11: error: redefinition of ‘const int google::GLOG_ERROR’
 const int GLOG_ERROR = 2;
           ^~~~~~~~~~
In file included from /home/anaconda3/envs/myenv/include/glog/logging.h:512:0,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/Headers.h:19,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/ActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/anaconda3/envs/myenv/include/glog/log_severity.h:47:44: note: ‘const int google::GLOG_ERROR’ previously defined here
 const int GLOG_INFO = 0, GLOG_WARNING = 1, GLOG_ERROR = 2, GLOG_FATAL = 3,
                                            ^~~~~~~~~~
In file included from /home/libtorch/include/c10/util/Logging.h:28:0,
                 from /home/libtorch/include/c10/core/TensorImpl.h:18,
                 from /home/libtorch/include/ATen/core/TensorBody.h:11,
                 from /home/libtorch/include/ATen/Tensor.h:3,
                 from /home/libtorch/include/ATen/Context.h:4,
                 from /home/libtorch/include/ATen/ATen.h:9,
                 from /home/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/libtorch/include/torch/script.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:5,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/libtorch/include/c10/util/logging_is_not_google_glog.h:21:11: error: redefinition of ‘const int google::GLOG_WARNING’
 const int GLOG_WARNING = 1;
           ^~~~~~~~~~~~
In file included from /home/anaconda3/envs/myenv/include/glog/logging.h:512:0,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/Headers.h:19,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/ActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/anaconda3/envs/myenv/include/glog/log_severity.h:47:26: note: ‘const int google::GLOG_WARNING’ previously defined here
 const int GLOG_INFO = 0, GLOG_WARNING = 1, GLOG_ERROR = 2, GLOG_FATAL = 3,
                          ^~~~~~~~~~~~
In file included from /home/libtorch/include/c10/util/Logging.h:28:0,
                 from /home/libtorch/include/c10/core/TensorImpl.h:18,
                 from /home/libtorch/include/ATen/core/TensorBody.h:11,
                 from /home/libtorch/include/ATen/Tensor.h:3,
                 from /home/libtorch/include/ATen/Context.h:4,
                 from /home/libtorch/include/ATen/ATen.h:9,
                 from /home/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/libtorch/include/torch/script.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:5,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/libtorch/include/c10/util/logging_is_not_google_glog.h:22:11: error: redefinition of ‘const int google::GLOG_INFO’
 const int GLOG_INFO = 0;
           ^~~~~~~~~
In file included from /home/anaconda3/envs/myenv/include/glog/logging.h:512:0,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/Headers.h:19,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/ActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/./reagent/serving/core/PytorchActionValueScorer.h:3,
                 from /home/nthai/ReAgent/serving/reagent/serving/core/PytorchActionValueScorer.cpp:1:
/home/anaconda3/envs/myenv/include/glog/log_severity.h:47:11: note: ‘const int google::GLOG_INFO’ previously defined here
 const int GLOG_INFO = 0, GLOG_WARNING = 1, GLOG_ERROR = 2, GLOG_FATAL = 3,
           ^~~~~~~~~
CMakeFiles/rasp-lib.dir/build.make:127: recipe for target 'CMakeFiles/rasp-lib.dir/reagent/serving/core/PytorchActionValueScorer.cpp.o' failed
make[2]: *** [CMakeFiles/rasp-lib.dir/reagent/serving/core/PytorchActionValueScorer.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/rasp-lib.dir/all' failed
make[1]: *** [CMakeFiles/rasp-lib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried mixing up include orders in the header files but it did not help. I also tried removing the const variables from the libtorch source but then I bumped into linking errors.

**Comment by kaiwenw** [comment] 2020-07-10 22:54
Hi @nthai, the issue is from libtorch and hopefully should be fixed by pytorch soon.
In the meantime, could you try earlier versions of libtorch?

**Comment by nthai** [comment] 2020-07-12 17:37
Hi @kaiwenw, thanks for the reply!

Earlier libtorch version works, eg.: `wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.5.1%2Bcpu.zip`

**Comment by malfet** [comment] 2020-07-16 20:30
@nthai can you please try if it is fixed in nightly that contains pytorch/pytorch#41504 ?

**Comment by kaiwenw** [comment] 2020-07-16 22:44
@malfet Thanks for the fix! Our CircleCI test shows Linux works, but MAC OS still fails with the error. Does it take another day to push?

**Comment by kaiwenw** [comment] 2020-07-18 01:15
@nthai This should be fixed now. Thanks @malfet!

**Closed by kaiwenw** 2020-07-18 01:15 UTC
